# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8714963f83aab28246b584d2f3f7dca1fc716aa341e463f714c75de8dc3b32baeea2aa9caffe46166594ae6585c9b3e845bad1d8461c6720de058376fc0bf31d

test:
  secret_key_base: 6910450a87fc346b897069a714cd59b4290563fd9ecf81d778115b2fda6f95459922095356de1f6bb22ff2735e20b4d9a5529b10addbf08b6e04057d562cef05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
